[2021-08-04 14:45:50,583] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T14:45:37.958228+00:00 [queued]>
[2021-08-04 14:45:50,597] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T14:45:37.958228+00:00 [queued]>
[2021-08-04 14:45:50,598] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:45:50,598] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 14:45:50,598] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:45:50,613] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): inaccurate> on 2021-08-04T14:45:37.958228+00:00
[2021-08-04 14:45:50,618] {standard_task_runner.py:52} INFO - Started process 2023 to run task
[2021-08-04 14:45:50,622] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', '2021-08-04T14:45:37.958228+00:00', '--job-id', '3027', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpugjgdht8', '--error-file', '/tmp/tmpenpr6mfz']
[2021-08-04 14:45:50,623] {standard_task_runner.py:77} INFO - Job 3027: Subtask inaccurate
[2021-08-04 14:45:50,662] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.inaccurate 2021-08-04T14:45:37.958228+00:00 [running]> on host 04479ea62028
[2021-08-04 14:45:50,720] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T14:45:37.958228+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T14:45:37.958228+00:00
[2021-08-04 14:45:50,720] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-04 14:45:50,721] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2021-08-04 14:45:50,729] {subprocess.py:74} INFO - Output:
[2021-08-04 14:45:50,730] {subprocess.py:78} INFO - inaccurate
[2021-08-04 14:45:50,731] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-04 14:45:50,757] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20210804T144537, start_date=20210804T144550, end_date=20210804T144550
[2021-08-04 14:45:50,782] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 14:45:50,796] {local_task_job.py:149} INFO - Task exited with return code 0
