[2021-08-04 14:06:08,236] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T14:05:54.460692+00:00 [queued]>
[2021-08-04 14:06:08,254] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T14:05:54.460692+00:00 [queued]>
[2021-08-04 14:06:08,255] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:06:08,255] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 14:06:08,255] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:06:08,262] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): inaccurate> on 2021-08-04T14:05:54.460692+00:00
[2021-08-04 14:06:08,266] {standard_task_runner.py:52} INFO - Started process 2360 to run task
[2021-08-04 14:06:08,269] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', '2021-08-04T14:05:54.460692+00:00', '--job-id', '2548', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp02k7r9y_', '--error-file', '/tmp/tmpn_qm5rgx']
[2021-08-04 14:06:08,270] {standard_task_runner.py:77} INFO - Job 2548: Subtask inaccurate
[2021-08-04 14:06:08,307] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.inaccurate 2021-08-04T14:05:54.460692+00:00 [running]> on host 04479ea62028
[2021-08-04 14:06:08,355] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T14:05:54.460692+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T14:05:54.460692+00:00
[2021-08-04 14:06:08,356] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-04 14:06:08,356] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2021-08-04 14:06:08,366] {subprocess.py:74} INFO - Output:
[2021-08-04 14:06:08,367] {subprocess.py:78} INFO - inaccurate
[2021-08-04 14:06:08,367] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-04 14:06:08,399] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20210804T140554, start_date=20210804T140608, end_date=20210804T140608
[2021-08-04 14:06:08,428] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 14:06:08,443] {local_task_job.py:149} INFO - Task exited with return code 0
