[2021-08-04 14:45:11,220] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T14:44:57.958228+00:00 [queued]>
[2021-08-04 14:45:11,234] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T14:44:57.958228+00:00 [queued]>
[2021-08-04 14:45:11,234] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:45:11,234] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 14:45:11,234] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:45:11,251] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): inaccurate> on 2021-08-04T14:44:57.958228+00:00
[2021-08-04 14:45:11,256] {standard_task_runner.py:52} INFO - Started process 1926 to run task
[2021-08-04 14:45:11,260] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', '2021-08-04T14:44:57.958228+00:00', '--job-id', '3007', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpkgp97ifk', '--error-file', '/tmp/tmpa1fopujv']
[2021-08-04 14:45:11,261] {standard_task_runner.py:77} INFO - Job 3007: Subtask inaccurate
[2021-08-04 14:45:11,313] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.inaccurate 2021-08-04T14:44:57.958228+00:00 [running]> on host 04479ea62028
[2021-08-04 14:45:11,466] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T14:44:57.958228+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T14:44:57.958228+00:00
[2021-08-04 14:45:11,467] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-04 14:45:11,468] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2021-08-04 14:45:11,482] {subprocess.py:74} INFO - Output:
[2021-08-04 14:45:11,482] {subprocess.py:78} INFO - inaccurate
[2021-08-04 14:45:11,483] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-04 14:45:11,570] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20210804T144457, start_date=20210804T144511, end_date=20210804T144511
[2021-08-04 14:45:11,642] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 14:45:11,678] {local_task_job.py:149} INFO - Task exited with return code 0
