[2021-08-04 12:38:54,817] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T12:38:51.434384+00:00 [queued]>
[2021-08-04 12:38:54,834] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T12:38:51.434384+00:00 [queued]>
[2021-08-04 12:38:54,834] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 12:38:54,834] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 12:38:54,834] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 12:38:54,842] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): inaccurate> on 2021-08-04T12:38:51.434384+00:00
[2021-08-04 12:38:54,845] {standard_task_runner.py:52} INFO - Started process 2785 to run task
[2021-08-04 12:38:54,848] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', '2021-08-04T12:38:51.434384+00:00', '--job-id', '41', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpwf25g6mj', '--error-file', '/tmp/tmp0xph_xuj']
[2021-08-04 12:38:54,849] {standard_task_runner.py:77} INFO - Job 41: Subtask inaccurate
[2021-08-04 12:38:54,886] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.inaccurate 2021-08-04T12:38:51.434384+00:00 [running]> on host 04479ea62028
[2021-08-04 12:38:54,942] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T12:38:51.434384+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-04T12:38:51.434384+00:00
[2021-08-04 12:38:54,945] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-04 12:38:54,947] {subprocess.py:63} INFO - Running command: ['bash', '-c', " echo 'inaccurate'"]
[2021-08-04 12:38:54,969] {subprocess.py:74} INFO - Output:
[2021-08-04 12:38:54,973] {subprocess.py:78} INFO - inaccurate
[2021-08-04 12:38:54,974] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-04 12:38:55,057] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20210804T123851, start_date=20210804T123854, end_date=20210804T123855
[2021-08-04 12:38:55,092] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 12:38:55,102] {local_task_job.py:149} INFO - Task exited with return code 0
