[2021-08-04 14:43:30,919] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T14:43:17.958228+00:00 [queued]>
[2021-08-04 14:43:30,933] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-08-04T14:43:17.958228+00:00 [queued]>
[2021-08-04 14:43:30,934] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:43:30,934] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-04 14:43:30,934] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 14:43:30,948] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): inaccurate> on 2021-08-04T14:43:17.958228+00:00
[2021-08-04 14:43:30,952] {standard_task_runner.py:52} INFO - Started process 1675 to run task
[2021-08-04 14:43:30,956] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', '2021-08-04T14:43:17.958228+00:00', '--job-id', '2957', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp8du3wxv0', '--error-file', '/tmp/tmpm1flhd09']
[2021-08-04 14:43:30,956] {standard_task_runner.py:77} INFO - Job 2957: Subtask inaccurate
[2021-08-04 14:43:30,993] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.inaccurate 2021-08-04T14:43:17.958228+00:00 [running]> on host 04479ea62028
[2021-08-04 14:43:31,037] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-08-04T14:43:17.958228+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-04T14:43:17.958228+00:00
[2021-08-04 14:43:31,038] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-04 14:43:31,039] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2021-08-04 14:43:31,047] {subprocess.py:74} INFO - Output:
[2021-08-04 14:43:31,048] {subprocess.py:78} INFO - inaccurate
[2021-08-04 14:43:31,048] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-04 14:43:31,077] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20210804T144317, start_date=20210804T144330, end_date=20210804T144331
[2021-08-04 14:43:31,101] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-04 14:43:31,129] {local_task_job.py:149} INFO - Task exited with return code 0
